services:
  - type: web
    name: ghost
    env: docker
    autoDeploy: false
    plan: free
    disk:
      name: ghost
      mountPath: /var/lib/ghost/content
      sizeGB: 10

    envVars:
      - key: database__client
        value: pg
      - key: database__connection__host
        value: db.ypwgvnqjgujjizzuosqw.supabase.co  # ← bruk din Supabase-host
      - key: database__connection__port
        value: 5432
      - key: database__connection__database
        value: postgres
      - key: database__connection__user
        value: postgres
      - key: database__connection__password
        value: C5KmtauUH6CnDwYS # ← sett inn passordet ditt her
      - key: url
        value: https://ghost-8hj6.onrender.com  # ← din Render-URL
